version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: base_app
    links:
      - db
      - redis
    command: sh -c "python manage.py collectstatic --noinput ; gunicorn -b :${DOCKER_EXPOSED_PORT} calc.wsgi:application"
    ports:
      - "${DOCKER_EXPOSED_PORT}:${DOCKER_EXPOSED_PORT}"
    mem_limit: 1G
  db:
    image: postgres:9.5.4
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=calc
      - POSTGRES_USER=calc_user
  redis:
    image: redis:3.2-alpine
  rq_worker:
    extends:
      file: docker-services.yml
      service: base_app
    links:
      - db
      - redis
    command: python manage.py rqworker
    mem_limit: 512M
  rq_scheduler:
    extends:
      file: docker-services.yml
      service: base_app
    links:
      - db
      - redis
    command: python manage.py rqscheduler
    environment:
      - IS_RQ_SCHEDULER=yup
    mem_limit: 512M
volumes:
  node-modules:
  python-venv:
  home:
  pgdata:
  # TODO: We might be able to just put the nltk-data in the home dir.
  nltk-data:
